apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    #    path: "/mnt/data"  # - for Unix/Linux
    #    path: "/mnt/host"  # - for Others
    #    path: "/run/desktop/mnt/data/c/temp/testfiles"   # - for Windows
    path: "/mnt/data"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_PASSWORD
              value: root
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-initdb
          configMap:
            name: postgres-initdb-cm
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-cm
data:
#  init.sql: |
#    CREATE DATABASE IF NOT EXISTS creatordb;
#    CREATE DATABASE IF NOT EXISTS articledb;
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
