server:
  port: 8082

spring:
  application:
    name: ARTICLE
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    url: jdbc:h2:mem:blog
    driverClassName: org.h2.Driver
    username: sa
    password:
    ddl-auto: create-drop
    pool-size: 30
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
    resilience4j:
      circuitbreaker:
        instances:
          external:
            event-consumer-buffer-size: 10
            failure-rate-threshold: 50
            minimum-number-of-calls: 5
            automatic-transition-from-open-to-half-open-enabled: true
            wait-duration-in-open-state: 5s
            permitted-number-of-calls-in-half-open-state: 3
            sliding-window-size: 10
            sliding-window-type: COUNT_BASED

#spring:
#  application:
#    name: ARTICLE
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/article