server:
  port: 8082

spring:
  application:
    name: ARTICLE
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    url: jdbc:h2:mem:blog
    driverClassName: org.h2.Driver
    username: sa
    password:
    ddl-auto: create-drop
    pool-size: 30
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


#spring:
#  application:
#    name: ARTICLE
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/article